root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/server"
  bin = "tmp/main.exe"
  full_bin = "tmp/main.exe"
  delay = 1000
  include_ext = ["go"]
  exclude_dir = ["tmp", "node_modules"]
  exclude_regex = ["_test\\.go"]

[log]
  time = true

[misc]
  clean_on_exit = true
